hello:hello.c
	gcc hello.c -o hello -lcs50
compare:compare.c
	gcc compare.c -o compare  -lcs50
agree:agree.c
	gcc agree.c -o agree  -lcs50
cat:cat.c
	gcc cat.c -o cat -lcs50
mario:mario.c
	gcc  mario.c -o mario -lcs50
calculator:calculator.c
	@gcc calculator.c -o calculator -lcs50
array:array.c	
	@gcc array.c -o array -lcs50
string:string.c	
	@gcc string.c -o string -lcs50

length:length.c
	@gcc length.c -o length -lcs50 

uppercase:uppercase.c
	@gcc uppercase.c -o uppercase -lcs50  

greet:greet.c
	@gcc greet.c -o greet -lcs50

search:search.c
	@gcc search.c -o search -lcs50
phonebook:phonebook.c	  
	@gcc phonebook.c -o phonebook -lcs50
iteration:iteration.c	
	@gcc iteration.c -o iteration -lcs50
recursion:recursion.c	
	@gcc recursion.c -o recursion -lcs50
adresses:adresses.c	
	@gcc adresses.c -o adresses -lcs50
copy:copy.c	
	@gcc copy.c -o copy -lcs50
memory:memory.c	
	@gcc memory.c -o memory -lcs50
testing:testing.c	
	@gcc testing.c -o testing -lcs50
contacts:contacts.c	
	@gcc contacts.c -o contacts -lcs50
cp:cp.c	
	@gcc cp.c -o cp -lcs50
list:list.c	
	@gcc -g list.c -o list -lcs50
llist:llist.c	
	@gcc -g llist.c -o llist -lcs50


